name: counter_strike_3
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=3.0.0 <4.0.0'

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.5
  firebase_core: ^2.20.0
  firebase_auth: ^4.9.0
  dio: ^5.2.1+1

flutter:
  uses-material-design: true
  generate: true



dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0