import 'dart:math';

class RealNameGenerator {
  final Random _random = Random();

  final List<String> firstNames = [
    'Afonso',
    'Alexandre',
    'Alice',
    'Amélia',
    'Ana',
    'Antônio',
    'Beatriz',
    'Bernardo',
    'Bianca',
    'Bruno',
    'Catarina',
    'Clara',
    'Davi',
    'Débora',
    'Eduardo',
    'Elena',
    'Emília',
    'Eva',
    'Felipe',
    'Fernanda',
    'Gabriel',
    'Giovanna',
    'Gustavo',
    'Helena',
    'Henrique',
    'Isabel',
    'Isabella',
    'João',
    'Joaquim',
    'Laura',
    'Leonor',
    'Lívia',
    'Lorenzo',
    'Luana',
    'Luiza',
    'Manuela',
    'Maria',
    'Mariana',
    'Matheus',
    'Miguel',
    'Pedro',
    'Rafael',
    'Rodrigo',
    'Sofia',
    'Valentina',
    'Vicente',
    'Vitória',
    'Yasmin',
    'Zé',
    'Mariana',
    'Lucas',
    'Cláudia',
    'Carlos',
    'Daniela',
    'Joana',
    'Fábio',
    'Marta',
    'Sara',
    'Rui',
    'Inês',
    'André',
    'Carolina',
    'Vasco',
    'Margarida',
    'Tiago',
    'Rafaela',
    'Luís',
    'Bárbara',
    'Tomás',
    'Matilde',
    'Ricardo',
    'Ana Beatriz',
    'Mafalda',
    'Cristiano',
    'Júlia',
    'João Miguel',
    'Filipa',
    'Jorge',
    'Rita',
    'Paulo',
    'Lara',
    'Renato',
    'Cátia',
    'Sónia',
    'Patrícia',
    'Raquel',
    'Carla',
    'Rúben',
    'Márcia',
    'Hugo',
    'Célia',
    'Liliana',
    'Nelson',
    'Tânia',
    'Andréia',
    'Elaine',
    'Vanessa',
    'Sueli',
    'Jéssica',
    'Fernando',
    'Luciana',
    'Adriana',
    'Elisabete',
    'Fernandes',
    'Luísa',
    'Antónia',
    'Fábio',
    'Cláudia',
    'Isabel',
    'Lucas',
    'Nuno',
    'Teresa',
    'Diogo',
    'Mário',
    'António',
    'Marta',
    'Helena',
    'Carina',
    'Bruno',
    'Carla',
    'Sofia',
    'Adélia',
    'Diana',
    'Cristina',
    'Sónia',
    'Ana Sofia',
    'Leonardo',
    'Marcelo',
    'Carlos',
    'Duarte',
    'Cátia',
    'Ana Luísa',
    'Bianca',
    'Davide',
    'Paula',
    'Gonçalo',
    'Ivone',
    'Alex',
    'Sara',
    'Micaela',
    'José',
    'Joana',
    'Tiago',
    'Ana Rita',
    'Sara',
    'André',
    'Fábio',
    'Margarida',
    'Ana',
    'Leonor',
    'Paulo',
    'Luís',
    'Ricardo',
    'Cristina',
    'Fernanda',
    'Susana',
    'Vânia',
    'Ana Paula',
    'Marta',
    'Inês',
    'Eduardo',
    'Laura',
    'Mariana',
    'Miguel',
    'Rita',
    'Marta',
    'Cristina',
    'Carla',
    'Ana Isabel',
    'Ana',
    'Nádia',
    'Marina',
    'Ana Catarina',
    'Sandra',
    'Sofia',
    'André',
    'Ana Margarida',
    'David',
    'Vanessa',
    'Ana Filipa',
    'Susana',
    'Nuno',
    'Tânia',
    'Sérgio',
    'Carlos',
    'Sílvia',
    'Carolina',
    'Mafalda',
    'Rui',
    'Marta',
    'Jéssica',
    'Rafaela',
    'Ana Carolina',
    'Daniela',
    'Vera',
    'Cristina',
    'Joaquim',
    'Tânia',
    'Ana Sofia',
    'Diana',
    'Ivo',
    'Vítor',
    'Liliana',
    'Paula',
    'Sara',
    'Bruno',
    'Ana Luísa',
    'Sara',
    'Manuel',
    'Isabel',
    'Lucas',
    'Teresa',
    'Ana',
    'Joana',
    'Ana Rita',
    'Rafael',
    'Ricardo',
    'Carla',
    'Catarina',
    'Joaquim',
    'Paulo',
    'Mariana',
    'Nelson',
    'Célia',
    'André',
    'Elaine',
    'Sueli',
    'Fábio',
    'Daniela',
    'Sara',
    'Marta',
    'Luciana',
    'Carlos',
    'Fernando',
    'Elisabete',
    'Lucas',
    'Nuno',
    'Teresa',
    'Fernandes',
    'Gonçalo',
    'Ana Beatriz',
    'Jorge',
    'Maria',
    'Marta',
    'Marcelo',
    'João Miguel',
    'Cátia',
    'Ivone',
    'Carina',
    'Alexandre',
    'Márcia',
    'Carla',
    'Gustavo',
    'Margarida',
    'Jéssica',
    'Diogo',
    'Cristina',
    'Andréia',
    'Fábio',
    'Giovanna',
    'Ana',
    'Alice',
    'Afonso',
    'Alexandre',
    'Ana',
    'Antônio',
    'Beatriz',
    'Bernardo',
    'Bianca',
    'Bruno',
    'Catarina',
    'Clara',
    'Davi',
    'Débora',
    'Eduardo',
    'Elena',
    'Emília',
    'Eva',
    'Felipe',
    'Fernanda',
    'Gabriel',
    'Giovanna',
    'Gustavo',
    'Helena',
    'Henrique',
    'Isabel',
    'Isabella',
    'João',
    'Joaquim',
    'Laura',
    'Leonor',
    'Lívia',
    'Lorenzo',
    'Luana',
    'Luiza',
    'Manuela',
    'Maria',
    'Mariana',
    'Matheus',
    'Miguel',
    'Pedro',
    'Rafael',
    'Rodrigo',
    'Sofia',
    'Valentina',
    'Vicente',
    'Vitória',
    'Yasmin',
    'Zé',
    'Mariana',
    'Lucas',
    'Cláudia',
    'Carlos',
    'Daniela',
    'Joana',
    'Fábio',
    'Marta',
    'Sara',
    'Rui',
    'Inês',
    'André',
    'Carolina',
    'Vasco',
    'Margarida',
    'Tiago',
    'Rafaela',
    'Luís',
    'Bárbara',
    'Tomás',
    'Matilde',
    'Ricardo',
    'Ana Beatriz',
    'Mafalda',
    'Cristiano',
    'Júlia',
    'João Miguel',
    'Filipa',
    'Jorge',
    'Rita',
    'Paulo',
    'Lara',
    'Renato',
    'Cátia',
    'Sónia',
    'Patrícia',
    'Raquel',
    'Carla',
    'Rúben',
    'Márcia',
    'Hugo',
    'Célia',
    'Liliana',
    'Nelson',
    'Tânia',
    'Andréia',
    'Elaine',
    'Vanessa',
    'Sueli',
    'Jéssica',
    'Fernando',
    'Luciana',
    'Adriana',
    'Elisabete',
    'Fernandes',
    'Luísa',
    'Antónia',
    'Fábio',
    'Cláudia',
    'Isabel',
    'Lucas',
    'Nuno',
    'Teresa',
    'Diogo',
    'Mário',
    'António',
    'Marta',
    'Helena',
    'Carina',
    'Bruno',
    'Carla',
    'Sofia',
    'Adélia',
    'Diana',
    'Cristina',
    'Sónia',
    'Ana Sofia',
    'Leonardo',
    'Marcelo',
    'Carlos',
    'Duarte',
    'Cátia',
    'Ana Luísa',
    'Bianca',
    'Davide',
    'Paula',
    'Gonçalo',
    'Ivone',
    'Alex',
    'Sara',
    'Micaela',
    'José',
    'Joana',
    'Tiago',
    'Ana Rita',
    'Sara',
    'André',
    'Fábio',
    'Margarida',
    'Ana',
    'Leonor',
    'Paulo',
    'Luís',
    'Ricardo',
    'Cristina',
    'Fernanda',
    'Susana',
    'Vânia',
    'Ana Paula',
    'Marta',
    'Inês',
    'Eduardo',
    'Laura',
    'Mariana',
    'Miguel',
    'Rita',
    'Marta',
    'Cristina',
    'Carla',
    'Ana Isabel',
    'Ana',
    'Nádia',
    'Marina',
    'Ana Catarina',
    'Sandra',
    'Sofia',
    'André',
    'Ana Margarida',
    'David',
    'Vanessa',
    'Ana Filipa',
    'Susana',
    'Nuno',
    'Tânia',
    'Sérgio',
    'Carlos',
    'Sílvia',
    'Carolina',
    'Mafalda',
    'Rui',
    'Marta',
    'Jéssica',
    'Rafaela',
    'Ana Carolina',
    'Daniela',
    'Vera',
    'Cristina',
    'Joaquim',
    'Tânia',
    'Ana Sofia',
    'Diana',
    'Ivo',
    'Vítor',
    'Liliana',
    'Paula',
    'Sara',
    'Bruno',
    'Ana Luísa',
    'Sara',
    'Manuel',
    'Isabel',
    'Lucas',
    'Teresa',
    'Ana',
    'Joana',
    'Ana Rita',
    'Rafael',
    'Ricardo',
    'Carla',
    'Catarina',
    'Joaquim',
    'Paulo',
    'Mariana',
    'Nelson',
    'Célia',
    'André',
    'Elaine',
    'Sueli',
    'Fábio',
    'Daniela',
    'Sara',
    'Marta',
    'Luciana',
    'Carlos',
    'Fernando',
    'Elisabete',
    'Lucas',
    'Nuno',
    'Teresa',
    'Fernandes',
    'Gonçalo',
    'Ana Beatriz',
    'Jorge',
    'Maria',
    'Marta',
    'Marcelo',
    'João Miguel',
    'Cátia',
    'Ivone',
    'Carina',
    'Alexandre',
    'Márcia',
    'Carla',
    'Gustavo',
    'Margarida',
    'Jéssica',
    'Diogo',
    'Cristina',
    'Andréia',
    'Fábio',
    'Giovanna',
    'Ana',
    'Alice',
  ];

  final List<String> lastNames = [
    'Silva', 'Santos', 'Oliveira', 'Souza', 'Pereira', 'Rodrigues', 'Almeida',
    'Nascimento', 'Fernandes', 'Gomes',
    'Martins', 'Barbosa', 'Ferreira', 'Ribeiro', 'Alves', 'Lima', 'Carvalho',
    'Costa', 'Cavalcante', 'Monteiro',
    'Correia', 'Andrade', 'Araújo', 'Vieira', 'Mendes', 'Carneiro', 'Cardoso',
    'Cunha', 'Dias', 'Melo', 'Pinto',
    'Moura', 'Sousa', 'Freitas', 'Morais', 'Castro', 'Gonçalves', 'Mesquita',
    'Abreu', 'Tavares', 'Campos', 'Cordeiro',
    'Pacheco', 'Viana', 'Duarte', 'Pires', 'Magalhães', 'Caldeira', 'Lobato',
    'Moreira', 'Camacho', 'Godinho', 'Escobar',
    'Macedo', 'Leal', 'Figueiredo', 'Prado', 'Sampaio', 'Aragão', 'Sá', 'Carmo',
    'Xavier', 'Fonseca', 'Guimarães',
    'Paiva', 'Sobral', 'Lemos', 'Pontes', 'Amorim', 'Peixoto', 'Machado',
    'Teixeira', 'Loureiro', 'Assunção', 'Madeira',
    'Sarmento', 'Castelo', 'Canuto', 'Passos', 'Trindade', 'Soares', 'Lage',
    'Albuquerque', 'Peregrino', 'Botelho',
    'Miranda', 'Vaz', 'Sá', 'Vidal', 'Paes', 'Furtado', 'Novais', 'Cavalcanti',
    'Araguaia', 'Salgado', 'Brito',
    'Otero', 'Antunes', 'Guedes', 'Domingues', 'Esteves', 'Bastos', 'Alencar',
    'Guterres', 'Farias', 'Lacerda',
    'Prazeres', 'Ventura', 'Nunes', 'Braga', 'Vasconcelos', 'Rocha', 'Leão',
    'Sobrinho', 'Pereira', 'Félix', 'Góis',
    'Torrado', 'Meirelles', 'Sotero', 'Peregrino', 'Cavalcanti', 'Macedo',
    'Arantes', 'Gusmão', 'Sobral', 'Freire',
    'Pádua', 'Penna', 'Machado', 'Garrido', 'Sá', 'Miranda', 'Faria', 'Ortega',
    'Nóbrega', 'Lins', 'Pizarro', 'Toledo',
    'Bacelar', 'Pimenta', 'Sodré', 'Coutinho', 'Brito', 'Pereira', 'Ramalho',
    'Mendes', 'Camacho', 'Mesquita', 'Câmara',
    'Guimarães', 'Azevedo', 'Estrada', 'Furtado', 'Brasil', 'Cabral', 'Fonseca',
    'Santos', 'Alves', 'Lima', 'Barbosa',
    'Cavalcante', 'Monteiro', 'Correia', 'Andrade', 'Araújo', 'Vieira',
    'Mendes', 'Carneiro', 'Cardoso', 'Cunha', 'Dias',
    'Melo', 'Pinto', 'Moura', 'Sousa', 'Freitas', 'Morais', 'Castro',
    'Gonçalves', 'Mesquita', 'Abreu', 'Tavares',
    'Campos', 'Cordeiro', 'Pacheco', 'Viana', 'Duarte', 'Pires', 'Magalhães',
    'Caldeira', 'Lobato', 'Moreira',
    'Camacho', 'Godinho', 'Escobar', 'Macedo', 'Leal', 'Figueiredo', 'Prado',
    'Sampaio', 'Aragão', 'Sá', 'Carmo',
    'Xavier', 'Fonseca', 'Guimarães', 'Paiva', 'Sobral', 'Lemos', 'Pontes',
    'Amorim', 'Peixoto', 'Machado',
    'Teixeira', 'Loureiro', 'Assunção', 'Madeira', 'Sarmento', 'Castelo',
    'Canuto', 'Passos', 'Trindade', 'Soares',
    'Lage', 'Albuquerque', 'Peregrino', 'Botelho', 'Miranda', 'Vaz', 'Sá',
    'Vidal', 'Paes', 'Furtado', 'Novais',
    'Cavalcanti', 'Araguaia', 'Salgado', 'Brito', 'Otero', 'Antunes', 'Guedes',
    'Domingues', 'Esteves', 'Bastos',
    'Alencar', 'Guterres', 'Farias', 'Lacerda', 'Prazeres', 'Ventura', 'Nunes',
    'Braga', 'Vasconcelos', 'Rocha',
    'Leão', 'Sobrinho', 'Pereira', 'Félix', 'Góis', 'Torrado', 'Meirelles',
    'Sotero', 'Peregrino', 'Cavalcanti',
    'Macedo', 'Arantes', 'Gusmão', 'Sobral', 'Freire', 'Pádua', 'Penna',
    'Machado', 'Garrido', 'Sá', 'Miranda',
    'Faria', 'Ortega', 'Nóbrega', 'Lins', 'Pizarro', 'Toledo', 'Bacelar',
    'Pimenta', 'Sodré', 'Coutinho', 'Brito',
    'Pereira', 'Ramalho', 'Mendes', 'Camacho', 'Mesquita', 'Câmara',
    'Guimarães', 'Azevedo', 'Estrada', 'Furtado',
    'Brasil', 'Cabral', 'Fonseca', 'Santos', 'Alves', 'Lima', 'Barbosa',
    'Cavalcante', 'Monteiro', 'Correia',
    'Andrade', 'Araújo', 'Vieira', 'Mendes', 'Carneiro', 'Cardoso', 'Cunha',
    'Dias', 'Melo', 'Pinto', 'Moura',
    'Sousa', 'Freitas', 'Morais', 'Castro', 'Gonçalves', 'Mesquita', 'Abreu',
    'Tavares', 'Campos', 'Cordeiro',
    'Pacheco', 'Viana', 'Duarte', 'Pires', 'Magalhães', 'Caldeira', 'Lobato',
    'Moreira', 'Camacho', 'Godinho',
    'Escobar', 'Macedo', 'Leal', 'Figueiredo', 'Prado', 'Sampaio', 'Aragão',
    'Sá', 'Carmo', 'Xavier', 'Fonseca',
    'Guimarães', 'Paiva', 'Sobral', 'Lemos', 'Pontes', 'Amorim', 'Peixoto',
    'Machado', 'Teixeira', 'Loureiro',
    'Assunção', 'Madeira', 'Sarmento', 'Castelo', 'Canuto', 'Passos',
    'Trindade', 'Soares', 'Lage', 'Albuquerque',
    'Peregrino', 'Botelho', 'Miranda', 'Vaz', 'Sá', 'Vidal', 'Paes', 'Furtado',
    'Novais', 'Cavalcanti', 'Araguaia',
    'Salgado', 'Brito', 'Otero', 'Antunes', 'Guedes', 'Domingues', 'Esteves',
    'Bastos', 'Alencar', 'Guterres',
    'Farias', 'Lacerda', 'Prazeres', 'Ventura', 'Nunes', 'Braga', 'Vasconcelos',
    'Rocha', 'Leão', 'Sobrinho',
    'Pereira', 'Félix', 'Góis', 'Torrado', 'Meirelles', 'Sotero', 'Peregrino',
    'Cavalcanti', 'Macedo', 'Arantes',
    'Gusmão', 'Sobral', 'Freire', 'Pádua', 'Penna', 'Machado', 'Garrido', 'Sá',
    'Miranda', 'Faria', 'Ortega',
    'Nóbrega', 'Lins', 'Pizarro', 'Toledo', 'Bacelar', 'Pimenta', 'Sodré',
    'Coutinho', 'Brito', 'Pereira',
    'Ramalho', 'Mendes', 'Camacho', 'Mesquita', 'Câmara', 'Guimarães',
    'Azevedo', 'Estrada', 'Furtado', 'Brasil',
    'Cabral', 'Fonseca', 'Santos', 'Alves', 'Lima', 'Barbosa', 'Cavalcante',
    'Monteiro', 'Correia', 'Andrade',
    'Araújo', 'Vieira', 'Mendes', 'Carneiro', 'Cardoso', 'Cunha', 'Dias',
    'Melo', 'Pinto', 'Moura', 'Sousa',
    'Freitas', 'Morais', 'Castro', 'Gonçalves', 'Mesquita', 'Abreu', 'Tavares',
    'Campos', 'Cordeiro', 'Pacheco',
    'Viana', 'Duarte', 'Pires', 'Magalhães', 'Caldeira', 'Lobato', 'Moreira',
    'Camacho', 'Godinho', 'Escobar',
    'Macedo', 'Leal', 'Figueiredo',
    // Add more last names here
  ];

  String generateRandomName() {
    String firstName = firstNames[_random.nextInt(firstNames.length)];
    String lastName = lastNames[_random.nextInt(lastNames.length)];

    String fullName = '$firstName $lastName';
    return fullName;
  }
}
